const lineWidth = ['interpolate', ['linear'], ['zoom'], 10, 0.6, 16, 4, 20, 18];
const roadCasingWidth = ['interpolate', ['linear'], ['zoom'], 10, 2.1, 16, 5.5, 20, 19.5];
const majorRoadCasingWidth = ['interpolate', ['linear'], ['zoom'], 10, 2.8, 16, 6.2, 20, 20.2];
const landmarkMinZoom = 12.2;
const communePoiMinZoom = 14.8;
const neighborhoodPoiMinZoom = 16.2;
const landmarkIconSize = ['interpolate', ['linear'], ['zoom'], 12, 0.86, 16, 0.98, 19, 1.08];
const landmarkTextSize = ['interpolate', ['linear'], ['zoom'], 12, 10, 16, 12, 19, 13];

const darkMapStyleObject = {
  version: 8,
  name: 'Tribuus Night',
  glyphs: 'mapbox://fonts/mapbox/{fontstack}/{range}.pbf',
  sprite: 'mapbox://sprites/mapbox/streets-v12',
  sources: {
    composite: {
      type: 'vector',
      url: 'mapbox://mapbox.mapbox-streets-v8',
    },
    terrain: {
      maxzoom: 14,
      tileSize: 512,
      type: 'raster-dem',
      url: 'mapbox://mapbox.mapbox-terrain-dem-v1',
    },
  },
  layers: [
    {
      id: 'background',
      type: 'background',
      paint: { 'background-color': '#34485E' },
    },
    {
      id: 'landcover',
      type: 'fill',
      source: 'composite',
      'source-layer': 'landuse',
      paint: {
        'fill-color': [
          'match', ['get', 'class'],
          'wood', '#096B63',
          'scrub', '#126D66',
          'grass', '#1B746B',
          'crop', '#2B665F',
          '#34485E',
        ],
        'fill-opacity': 0.88,
      },
    },
    {
      id: 'terrain-shade',
      type: 'hillshade',
      source: 'terrain',
      paint: {
        'hillshade-accent-color': '#1A6965',
        'hillshade-exaggeration': 0.2,
        'hillshade-highlight-color': '#52667A',
        'hillshade-illumination-direction': 315,
        'hillshade-shadow-color': '#263A50',
      },
    },
    {
      id: 'parks',
      type: 'fill',
      source: 'composite',
      'source-layer': 'landuse',
      filter: ['match', ['get', 'class'], ['park', 'pitch', 'grass', 'cemetery'], true, false],
      paint: { 'fill-color': '#087168', 'fill-opacity': 0.94, 'fill-outline-color': '#16857B' },
    },
    {
      id: 'water',
      type: 'fill',
      source: 'composite',
      'source-layer': 'water',
      paint: { 'fill-color': '#25478C' },
    },
    {
      id: 'buildings',
      type: 'fill',
      source: 'composite',
      'source-layer': 'building',
      minzoom: 13,
      paint: {
        'fill-color': '#3D5065',
        'fill-opacity': 0.82,
        'fill-outline-color': '#53677C',
      },
    },
    {
      id: 'road-casing',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      paint: {
        'line-color': '#52677D',
        'line-opacity': 0.9,
        'line-width': roadCasingWidth,
      },
      layout: { 'line-cap': 'round', 'line-join': 'round' },
    },
    {
      id: 'major-road-casing',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      filter: ['match', ['get', 'class'], ['motorway', 'motorway_link', 'trunk', 'trunk_link', 'primary', 'primary_link'], true, false],
      paint: {
        'line-color': '#70859B',
        'line-width': majorRoadCasingWidth,
      },
      layout: { 'line-cap': 'round', 'line-join': 'round' },
    },
    {
      id: 'major-roads',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      filter: ['match', ['get', 'class'], ['motorway', 'motorway_link', 'trunk', 'trunk_link', 'primary', 'primary_link'], true, false],
      paint: {
        'line-color': '#9BAEC0',
        'line-width': lineWidth,
      },
      layout: { 'line-cap': 'round', 'line-join': 'round' },
    },
    {
      id: 'roads',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      filter: ['match', ['get', 'class'], ['motorway', 'motorway_link', 'trunk', 'trunk_link', 'primary', 'primary_link'], false, true],
      paint: { 'line-color': '#60758A', 'line-width': lineWidth },
      layout: { 'line-cap': 'round', 'line-join': 'round' },
    },
    {
      id: 'road-labels',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'road',
      minzoom: 12,
      layout: {
        'symbol-placement': 'line',
        'text-field': ['coalesce', ['get', 'name_es'], ['get', 'name']],
        'text-font': ['DIN Pro Medium', 'Arial Unicode MS Regular'],
        'text-size': 11,
      },
      paint: {
        'text-color': '#D4DDE5',
        'text-halo-color': '#34485E',
        'text-halo-width': 1.5,
      },
    },
    {
      id: 'natural-landform-icons',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'natural_label',
      minzoom: landmarkMinZoom,
      filter: ['all', ['==', ['get', 'class'], 'landform'], ['match', ['get', 'maki'], ['mountain', 'volcano'], true, false], ['<=', ['get', 'filterrank'], 1]],
      layout: {
        'icon-allow-overlap': false,
        'icon-ignore-placement': false,
        'icon-image': ['get', 'maki'],
        'icon-padding': 18,
        'icon-size': landmarkIconSize,
        'symbol-sort-key': ['coalesce', ['get', 'filterrank'], 5],
        'symbol-avoid-edges': true,
        'text-anchor': 'top',
        'text-allow-overlap': false,
        'text-field': ['coalesce', ['get', 'name_es'], ['get', 'name']],
        'text-font': ['DIN Pro Medium', 'Arial Unicode MS Regular'],
        'text-offset': [0, 1.75],
        'text-optional': true,
        'text-padding': 12,
        'text-size': landmarkTextSize,
      },
      paint: {
        'icon-color': '#42C990',
        'icon-halo-color': '#34485E',
        'icon-halo-width': 2,
        'text-color': '#A9E7CA',
        'text-halo-color': '#34485E',
        'text-halo-width': 1.5,
      },
    },
    {
      id: 'nature-poi-icons',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      minzoom: landmarkMinZoom,
      filter: ['all', ['match', ['get', 'maki'], ['park', 'garden', 'dog-park', 'picnic-site', 'campsite', 'viewpoint'], true, false], ['<=', ['get', 'filterrank'], 1]],
      layout: {
        'icon-allow-overlap': false,
        'icon-ignore-placement': false,
        'icon-image': ['get', 'maki'],
        'icon-padding': 18,
        'icon-size': landmarkIconSize,
        'symbol-sort-key': ['coalesce', ['get', 'filterrank'], 5],
        'symbol-avoid-edges': true,
        'text-anchor': 'top',
        'text-allow-overlap': false,
        'text-field': ['coalesce', ['get', 'name_es'], ['get', 'name']],
        'text-font': ['DIN Pro Medium', 'Arial Unicode MS Regular'],
        'text-offset': [0, 1.75],
        'text-optional': true,
        'text-padding': 12,
        'text-size': landmarkTextSize,
      },
      paint: {
        'icon-color': '#42C990',
        'icon-halo-color': '#34485E',
        'icon-halo-width': 2,
        'text-color': '#A9E7CA',
        'text-halo-color': '#34485E',
        'text-halo-width': 1.5,
      },
    },
    {
      id: 'cultural-poi-icons',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      minzoom: landmarkMinZoom,
      filter: ['all', ['match', ['get', 'maki'], ['museum', 'theatre', 'stadium', 'place-of-worship', 'religious-christian', 'religious-jewish', 'religious-muslim', 'monument', 'art-gallery', 'library'], true, false], ['<=', ['get', 'filterrank'], 1]],
      layout: {
        'icon-allow-overlap': false,
        'icon-ignore-placement': false,
        'icon-image': ['get', 'maki'],
        'icon-padding': 18,
        'icon-size': landmarkIconSize,
        'symbol-sort-key': ['coalesce', ['get', 'filterrank'], 5],
        'symbol-avoid-edges': true,
        'text-anchor': 'top',
        'text-allow-overlap': false,
        'text-field': ['coalesce', ['get', 'name_es'], ['get', 'name']],
        'text-font': ['DIN Pro Medium', 'Arial Unicode MS Regular'],
        'text-offset': [0, 1.75],
        'text-optional': true,
        'text-padding': 12,
        'text-size': landmarkTextSize,
      },
      paint: {
        'icon-color': '#B88AFF',
        'icon-halo-color': '#34485E',
        'icon-halo-width': 2,
        'text-color': '#D6C2FF',
        'text-halo-color': '#34485E',
        'text-halo-width': 1.5,
      },
    },
    {
      id: 'commune-nature-poi-icons',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      minzoom: communePoiMinZoom,
      filter: ['all', ['match', ['get', 'maki'], ['park', 'garden', 'dog-park', 'picnic-site', 'campsite', 'viewpoint'], true, false], ['>', ['get', 'filterrank'], 1], ['<=', ['get', 'filterrank'], 3]],
      layout: {
        'icon-allow-overlap': false,
        'icon-ignore-placement': false,
        'icon-image': ['get', 'maki'],
        'icon-padding': 15,
        'icon-size': landmarkIconSize,
        'symbol-sort-key': ['coalesce', ['get', 'filterrank'], 6],
        'symbol-avoid-edges': true,
        'text-anchor': 'top',
        'text-allow-overlap': false,
        'text-field': ['coalesce', ['get', 'name_es'], ['get', 'name']],
        'text-font': ['DIN Pro Medium', 'Arial Unicode MS Regular'],
        'text-offset': [0, 1.75],
        'text-optional': true,
        'text-padding': 10,
        'text-size': landmarkTextSize,
      },
      paint: { 'icon-color': '#42C990', 'icon-halo-color': '#34485E', 'icon-halo-width': 2, 'text-color': '#A9E7CA', 'text-halo-color': '#34485E', 'text-halo-width': 1.5 },
    },
    {
      id: 'commune-cultural-poi-icons',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      minzoom: communePoiMinZoom,
      filter: ['all', ['match', ['get', 'maki'], ['museum', 'theatre', 'stadium', 'place-of-worship', 'religious-christian', 'religious-jewish', 'religious-muslim', 'monument', 'art-gallery', 'library'], true, false], ['>', ['get', 'filterrank'], 1], ['<=', ['get', 'filterrank'], 3]],
      layout: {
        'icon-allow-overlap': false,
        'icon-ignore-placement': false,
        'icon-image': ['get', 'maki'],
        'icon-padding': 15,
        'icon-size': landmarkIconSize,
        'symbol-sort-key': ['coalesce', ['get', 'filterrank'], 6],
        'symbol-avoid-edges': true,
        'text-anchor': 'top',
        'text-allow-overlap': false,
        'text-field': ['coalesce', ['get', 'name_es'], ['get', 'name']],
        'text-font': ['DIN Pro Medium', 'Arial Unicode MS Regular'],
        'text-offset': [0, 1.75],
        'text-optional': true,
        'text-padding': 10,
        'text-size': landmarkTextSize,
      },
      paint: { 'icon-color': '#B88AFF', 'icon-halo-color': '#34485E', 'icon-halo-width': 2, 'text-color': '#D6C2FF', 'text-halo-color': '#34485E', 'text-halo-width': 1.5 },
    },
    {
      id: 'neighborhood-nature-poi-icons',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      minzoom: neighborhoodPoiMinZoom,
      filter: ['all', ['match', ['get', 'maki'], ['park', 'garden', 'dog-park', 'picnic-site', 'campsite', 'viewpoint'], true, false], ['>', ['get', 'filterrank'], 3], ['<=', ['get', 'filterrank'], 5]],
      layout: {
        'icon-allow-overlap': false,
        'icon-ignore-placement': false,
        'icon-image': ['get', 'maki'],
        'icon-padding': 12,
        'icon-size': landmarkIconSize,
        'symbol-sort-key': ['coalesce', ['get', 'filterrank'], 7],
        'symbol-avoid-edges': true,
        'text-anchor': 'top',
        'text-allow-overlap': false,
        'text-field': ['coalesce', ['get', 'name_es'], ['get', 'name']],
        'text-font': ['DIN Pro Medium', 'Arial Unicode MS Regular'],
        'text-offset': [0, 1.75],
        'text-optional': true,
        'text-padding': 8,
        'text-size': landmarkTextSize,
      },
      paint: { 'icon-color': '#42C990', 'icon-halo-color': '#34485E', 'icon-halo-width': 2, 'text-color': '#A9E7CA', 'text-halo-color': '#34485E', 'text-halo-width': 1.5 },
    },
    {
      id: 'neighborhood-cultural-poi-icons',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      minzoom: neighborhoodPoiMinZoom,
      filter: ['all', ['match', ['get', 'maki'], ['museum', 'theatre', 'stadium', 'place-of-worship', 'religious-christian', 'religious-jewish', 'religious-muslim', 'monument', 'art-gallery', 'library'], true, false], ['>', ['get', 'filterrank'], 3], ['<=', ['get', 'filterrank'], 5]],
      layout: {
        'icon-allow-overlap': false,
        'icon-ignore-placement': false,
        'icon-image': ['get', 'maki'],
        'icon-padding': 12,
        'icon-size': landmarkIconSize,
        'symbol-sort-key': ['coalesce', ['get', 'filterrank'], 7],
        'symbol-avoid-edges': true,
        'text-anchor': 'top',
        'text-allow-overlap': false,
        'text-field': ['coalesce', ['get', 'name_es'], ['get', 'name']],
        'text-font': ['DIN Pro Medium', 'Arial Unicode MS Regular'],
        'text-offset': [0, 1.75],
        'text-optional': true,
        'text-padding': 8,
        'text-size': landmarkTextSize,
      },
      paint: { 'icon-color': '#B88AFF', 'icon-halo-color': '#34485E', 'icon-halo-width': 2, 'text-color': '#D6C2FF', 'text-halo-color': '#34485E', 'text-halo-width': 1.5 },
    },
    {
      id: 'place-labels',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'place_label',
      layout: {
        'text-field': ['coalesce', ['get', 'name_es'], ['get', 'name']],
        'text-font': ['DIN Pro Medium', 'Arial Unicode MS Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 8, 11, 14, 15],
      },
      paint: {
        'text-color': '#E5EBF0',
        'text-halo-color': '#34485E',
        'text-halo-width': 1.5,
      },
    },
  ],
};

const lightLayerPaint: Record<string, Record<string, unknown>> = {
  background: { 'background-color': '#F1EFE8' },
  landcover: {
    'fill-color': [
      'match', ['get', 'class'],
      'wood', '#91D287',
      'scrub', '#B8DFA9',
      'grass', '#CBE9BE',
      'crop', '#DDEACA',
      '#E9E7DF',
    ],
    'fill-opacity': 0.88,
  },
  'terrain-shade': {
    'hillshade-accent-color': '#4E9D52',
    'hillshade-exaggeration': 0.18,
    'hillshade-highlight-color': '#F7F5ED',
    'hillshade-illumination-direction': 315,
    'hillshade-shadow-color': '#57955A',
  },
  parks: { 'fill-color': '#8FD486', 'fill-opacity': 0.92, 'fill-outline-color': '#5DAF62' },
  water: { 'fill-color': '#559FE7' },
  buildings: { 'fill-color': '#E7E4DF', 'fill-opacity': 0.76, 'fill-outline-color': '#DAD7D1' },
  'road-casing': { 'line-color': '#D5D2C9', 'line-opacity': 0.86, 'line-width': ['+', lineWidth, 1.5] },
  'major-road-casing': { 'line-color': '#E3AA60', 'line-width': ['+', lineWidth, 2.2] },
  'major-roads': { 'line-color': '#F4CB74', 'line-width': lineWidth },
  roads: { 'line-color': '#FFFFFF', 'line-width': lineWidth },
  'road-labels': { 'text-color': '#656566', 'text-halo-color': '#F8F7F1', 'text-halo-width': 1.5 },
  'natural-landform-icons': { 'icon-color': '#2D8E45', 'icon-halo-color': '#F8F7F1', 'icon-halo-width': 2, 'text-color': '#236E39', 'text-halo-color': '#F8F7F1', 'text-halo-width': 1.5 },
  'nature-poi-icons': { 'icon-color': '#2D8E45', 'icon-halo-color': '#F8F7F1', 'icon-halo-width': 2, 'text-color': '#236E39', 'text-halo-color': '#F8F7F1', 'text-halo-width': 1.5 },
  'cultural-poi-icons': { 'icon-color': '#7357C8', 'icon-halo-color': '#F8F7F1', 'icon-halo-width': 2, 'text-color': '#5D45A8', 'text-halo-color': '#F8F7F1', 'text-halo-width': 1.5 },
  'commune-nature-poi-icons': { 'icon-color': '#2D8E45', 'icon-halo-color': '#F8F7F1', 'icon-halo-width': 2, 'text-color': '#236E39', 'text-halo-color': '#F8F7F1', 'text-halo-width': 1.5 },
  'commune-cultural-poi-icons': { 'icon-color': '#7357C8', 'icon-halo-color': '#F8F7F1', 'icon-halo-width': 2, 'text-color': '#5D45A8', 'text-halo-color': '#F8F7F1', 'text-halo-width': 1.5 },
  'neighborhood-nature-poi-icons': { 'icon-color': '#2D8E45', 'icon-halo-color': '#F8F7F1', 'icon-halo-width': 2, 'text-color': '#236E39', 'text-halo-color': '#F8F7F1', 'text-halo-width': 1.5 },
  'neighborhood-cultural-poi-icons': { 'icon-color': '#7357C8', 'icon-halo-color': '#F8F7F1', 'icon-halo-width': 2, 'text-color': '#5D45A8', 'text-halo-color': '#F8F7F1', 'text-halo-width': 1.5 },
  'place-labels': { 'text-color': '#4E5965', 'text-halo-color': '#F8F7F1', 'text-halo-width': 1.5 },
};

const lightMapStyleObject = {
  ...darkMapStyleObject,
  name: 'Tribuus Light',
  layers: darkMapStyleObject.layers.map((layer) => ({
    ...layer,
    ...(layer.id === 'landcover' ? { 'source-layer': 'landcover' } : {}),
    ...(layer.id === 'road-labels' ? { 'source-layer': 'road_label' } : {}),
    paint: { ...layer.paint, ...(lightLayerPaint[layer.id] ?? {}) },
  })),
};

export const mapStyles = {
  dark: JSON.stringify(darkMapStyleObject),
  light: JSON.stringify(lightMapStyleObject),
} as const;
